services:
  web:
    build: .
    container_name: cms_image_pipeline_main
    environment:
      PORT: 9003
    ports:
      - "9003:9003"
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    env_file:
      - ${ENV_FILE:-.env.main}
    networks:
      - cms
    restart: unless-stopped

networks:
  cms:
    name: cms_main
